#!/bin/sh
if [ "$1" = "enable" ]; then
	dir="/home/debian/evt-bbb" # this should be changed to be dynamic
	if [ "$2" = "wifi" ]; then
		wdir="$dir/wifi"
		systemctl stop hostapd
		cp "$wdir/interfaces" "/etc/network/interfaces"
		cat "$wdir/resolv.conf" >> "/etc/resolv.conf"
		cp "$wdir/dnsmasq.conf" "/etc/dnsmasq.conf"
		systemctl start NetworkManager
	elif [ "$2" = "ap" ]; then
		systemctl stop hostapd
	else
		echo "unknown option '$2'; available options are:"
		echo "    nm, ap"
	fi
else
	echo "unknown command '$1'"
fi
